name: Publish to PyPI

on:
  workflow_dispatch: # Enable manual runs

jobs:

  # Run tests before publishing
  call_tests:
    uses: ./.github/workflows/tests.yml

  publish_to_pypi:
    runs-on: ubuntu-latest
    needs: call_tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Dependencies
        run: |
          poetry install

      #      - name: Update Version
      #        run: |
      #          poetry version patch # Use 'minor' or 'major' for minor or major version bumps

      - name: Build and Publish Package
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build
